### ISSUE TITLE
GitHub Pages 사용방법 확인

### ISSUE THREAD

**Issue by YoungestSalon** [DataItGirlsWiki/dataitgirlswiki.github.io#2]
- [x] GitHub Pages 사용방법 확인
- [x] 참조 : https://help.github.com/categories/github-pages-basics/

**Comment by chaewonkang** [comment]
은지님 최고에요! 🙆🏻감사합니다.

**Comment by YoungestSalon** [comment]
8/15 GitHub Pages 사용방법 확인 완료
